//! Ctrl+click: load the nearest S-band NEXRAD.
//!
//! The word that carries the whole feature is *S-band*. Around every large
//! airport in the country there is also a TDWR, a C-band terminal radar
//! sitting fifteen to thirty kilometres from downtown — closer to the city
//! than the WSR-88D almost every time. A plain nearest-site search therefore
//! answers "Dallas" with TDAL, "Chicago" with TORD and "Atlanta" with TATL,
//! which is the opposite of what was asked for. A TDWR has roughly ninety
//! kilometres of Doppler range and attenuates badly in the heavy rain that a
//! severe-weather workflow is looking at, so it is a supplement, never the
//! radar the map falls back to (Vasiloff, S. V., 2001: Improving tornado
//! warnings with the Federal Aviation Administration's Terminal Doppler
//! Weather Radar. *Wea. Forecasting*, **16**; Istok, M. J., and coauthors,
//! 2009: Terminal Doppler Weather Radar for NWS operations. *25th Conf. on
//! IIPS*, Amer. Meteor. Soc.). Terminal radars are consequently not ranked
//! here at all — they are removed, and the ranking runs over WSR-88Ds only.
//!
//! This module is the decision and nothing else. It draws no pixels, holds no
//! egui context and starts no download: it takes a click's modifiers, a
//! clicked latitude and longitude, and the site catalog the application has
//! already loaded, and it answers which site to switch to. That is what makes
//! the part that is actually hard to get right — which radar wins where —
//! checkable against the real published catalog instead of against a picture.
//!
//! # Ported from BowEcho, and where this departs
//!
//! BowEcho spells the same gesture `ctrl_best_radar_click` (`app_ui/src/
//! main.rs`) feeding `best_radar_candidates` (`app_ui/src/sites_ui.rs`).
//! What it actually does:
//!
//!   * chord: `ctrl && !alt && !shift`;
//!   * take every site within 460 km whose catalogued kind is `Wsr88d` or
//!     `Intl` — `Tdwr` and `Research` are dropped before ranking;
//!   * score each one by the 0.5 degree beam-centre height at that range and
//!     sort ascending, so the pick is "the radar that sees lowest here";
//!   * classify TDWRs from an explicit id table, *not* from the `'T'`
//!     prefix, because TJUA (San Juan) is a T-prefixed WSR-88D;
//!   * and — the part that is easiest to leave out and that undoes the rest —
//!     take the click away from the site-marker hit-test while the chord is
//!     held (`plain_map_click_allowed`), so a marker cannot swallow the
//!     gesture. [`site_marker_click_allowed`] is that rule.
//!
//! The judgement ported here is all of that. Three deliberate departures:
//!
//!   1. **Ranking is by great-circle distance, and the beam height is
//!      reported rather than sorted on.** At a fixed elevation angle the
//!      4/3-earth beam height is strictly increasing in range, so ordering by
//!      beam height and ordering by distance are the same ordering; BowEcho's
//!      sort key implies the beam height adds information to the *choice*
//!      that it does not. [`SiteChoice::beam_height_m`] is carried anyway,
//!      because it is the number worth putting in the status line.
//!   2. **No international registry.** This workspace's catalog is the NWS
//!      station list only, so there is no `Intl` arm to keep.
//!   3. **Classification comes from the published `stationType`, not from a
//!      frozen prefix heuristic.** See below. The visible consequence is
//!      TLKA2: BowEcho lists it as a TDWR, because its seed table was
//!      generated by running the old `'T'`-prefix rule over the catalog.
//!      TLKA2 is a wind profiler.
//!
//! # How an S-band site is identified *here*
//!
//! The catalog this application carries ([`LocatedSite`]) has an id, a name
//! and a position. It has no band field and no network enum, because
//! `data_source::fetch_weather_gov_radar_sites` keeps only those four fields
//! out of the station feed. The feed itself does carry the discriminator —
//! `properties.stationType`, one of `WSR-88D`, `TDWR` or `Profiler` — so the
//! honest move is to bring that field's *content* into this module as data
//! and classify by id lookup, exactly as BowEcho does.
//!
//! [`TDWR_SITE_IDS`] and [`PROFILER_SITE_IDS`] are therefore transcriptions
//! of `https://api.weather.gov/radar/stations`, retrieved 2026-08-18: 208
//! stations, 159 `WSR-88D`, 45 `TDWR`, 4 `Profiler`. The transcription is
//! pinned by `classification_agrees_with_the_published_station_type`, which
//! replays the whole retrieved catalog through [`classify_site`].
//!
//! **How much work those two tables actually do, measured rather than
//! assumed.** Very little, today. Deleting either one changes no answer for
//! any of the 208 published stations, because the structural fallback below
//! already lands them all correctly: every published TDWR has a
//! four-character `T` id, and all four profilers have five-character ids.
//! `the_structural_rule_alone_already_classifies_the_published_catalog`
//! records that, so nobody reads the tables as the thing keeping TDAL out of
//! Dallas — the `'T'` prefix rule and the single TJUA exception
//! ([`S_BAND_WITH_A_TERMINAL_PREFIX`]) are what do that. The tables are kept
//! for the case the
//! structural rule cannot survive — a terminal radar commissioned under an id
//! that does not begin with `T`, which the fallback would silently admit as a
//! WSR-88D — but no test can pin that, because no id in the published catalog
//! needs it. What *is* pinned is the harm a table can do:
//! `no_exclusion_table_entry_is_a_published_wsr88d` fails if a typo ever puts
//! a WSR-88D id in one, which would quietly delete that radar from the
//! gesture.
//!
//! Two things the id alone will not tell you, and which is why the tables
//! exist:
//!
//!   * **TJUA is a WSR-88D.** San Juan's S-band radar has a `T` prefix. The
//!     TDWR twenty kilometres away is TSJU. A `'T'`-prefix rule leaves Puerto
//!     Rico with no radar at all under this gesture.
//!   * **`Profiler` rows are not radars.** AWPA2, HWPA2, ROCO2 and TLKA2 are
//!     wind profilers in the same feed and serve no Level II volume, so they
//!     must not be offered either.
//!
//! An id in neither table is classified structurally, and the fallback is
//! chosen to fail safe for this feature: an unrecognised four-character id
//! beginning with `T` is treated as terminal (it loses), an unrecognised id
//! that is not four characters is treated as neither (it loses), and only an
//! unrecognised four-character id with a non-`T` prefix is admitted as a
//! WSR-88D — which is the shape every new S-band site takes, KHDC being the
//! most recent example.

use eframe::egui;

use crate::sites_service::LocatedSite;

/// How far from the click a WSR-88D may be and still be offered, in
/// kilometres.
///
/// 460 km is the WSR-88D's unambiguous surveillance range — the outer edge of
/// the reflectivity sweep, beyond which the site has nothing to show at this
/// point (Crum, T. D., and R. L. Alberty, 1993: The WSR-88D and the WSR-88D
/// Operational Support Facility. *Bull. Amer. Meteor. Soc.*, **74**,
/// 1669-1687). Past it the answer is "no radar covers this", not "here is a
/// distant radar", and BowEcho fences the same gesture at the same range.
pub const MAX_SITE_RANGE_KM: f64 = 460.0;

/// The lowest surveillance tilt of every operational VCP, in degrees. Used
/// only to report how high the beam is over the clicked point.
const LOWEST_TILT_DEG: f64 = 0.5;

/// Generous ceiling for the ground-range-to-slant-range inversion. Larger
/// than [`MAX_SITE_RANGE_KM`] so the inversion is never the thing that
/// rejects a site.
const MAX_SLANT_RANGE_M: f64 = 1_000_000.0;

/// Mean earth radius for the great-circle distance, in kilometres. The IUGG
/// mean radius, matching `render2d::beam::EARTH_RADIUS_M`.
const EARTH_RADIUS_KM: f64 = 6371.0;

/// What a catalog id turns out to be.
///
/// Deliberately not `#[non_exhaustive]`: adding a class should be a compile
/// error at every site that decides what is loadable.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SiteClass {
    /// S-band NEXRAD. The only class this gesture will load.
    Wsr88d,
    /// C-band FAA terminal Doppler radar.
    Tdwr,
    /// In the station feed but not a scanning weather radar: the four wind
    /// profilers, and anything whose id does not have a NEXRAD shape.
    Other,
}

impl SiteClass {
    /// Whether a site of this class may win a Ctrl+click.
    pub fn is_s_band_nexrad(self) -> bool {
        matches!(self, Self::Wsr88d)
    }
}

/// The 45 stations published as `stationType: "TDWR"`, plus one retired id.
///
/// TPBI is not in the current feed: West Palm Beach's terminal radar is
/// listed as TDJT. The old id is kept because
/// `data_source::FALLBACK_SITE_IDS` — the catalog this application falls back
/// to when the station feed cannot be reached — still carries TPBI, and a
/// site reaching this module from that path must classify the same way.
pub const TDWR_SITE_IDS: &[&str] = &[
    "TADW", "TATL", "TBNA", "TBOS", "TBWI", "TCLT", "TCMH", "TCVG", "TDAL", "TDAY", "TDCA", "TDEN",
    "TDFW", "TDJT", "TDTW", "TEWR", "TFLL", "THOU", "TIAD", "TIAH", "TICH", "TIDS", "TJFK", "TLAS",
    "TLVE", "TMCI", "TMCO", "TMDW", "TMEM", "TMIA", "TMKE", "TMSP", "TMSY", "TOKC", "TORD", "TPBI",
    "TPHL", "TPHX", "TPIT", "TRDU", "TSDF", "TSJU", "TSLC", "TSTL", "TTPA", "TTUL",
];

/// The four stations published as `stationType: "Profiler"`. They are in the
/// radar station feed, they have positions, and they are not radars.
pub const PROFILER_SITE_IDS: &[&str] = &["AWPA2", "HWPA2", "ROCO2", "TLKA2"];

/// The one S-band NEXRAD whose id begins with `T`: San Juan, Puerto Rico.
/// Called out by name because it is the single reason a prefix rule cannot be
/// used here.
pub const S_BAND_WITH_A_TERMINAL_PREFIX: &str = "TJUA";

/// What kind of station a catalog id names.
///
/// Table lookup first (that is the published `stationType`), then a
/// structural fallback for an id the tables have not seen. See the module
/// documentation for why the fallback leans the way it does.
pub fn classify_site(id: &str) -> SiteClass {
    let id = id.trim().to_ascii_uppercase();
    if PROFILER_SITE_IDS.contains(&id.as_str()) {
        return SiteClass::Other;
    }
    if TDWR_SITE_IDS.contains(&id.as_str()) {
        return SiteClass::Tdwr;
    }
    if id == S_BAND_WITH_A_TERMINAL_PREFIX {
        return SiteClass::Wsr88d;
    }
    let bytes = id.as_bytes();
    if bytes.len() != 4 || !bytes.iter().all(u8::is_ascii_alphanumeric) {
        return SiteClass::Other;
    }
    if bytes[0] == b'T' {
        SiteClass::Tdwr
    } else {
        SiteClass::Wsr88d
    }
}

/// Whether these modifiers are the "nearest S-band radar" chord.
///
/// **Ctrl alone, and nothing else with it.** Ported unchanged from BowEcho's
/// `ctrl_best_radar_click`, which is `ctrl && !alt && !shift`, so an analyst
/// moving between the two applications keeps one habit.
///
/// What this must not disturb, all of it checked in this module's tests:
///
///   * **Ctrl+scroll is the pane zoom** (`pane_canvas::wheel_zoom_factor`).
///     No conflict: that reads `Event::MouseWheel`, this reads a pointer
///     click. The two can even happen in the same frame — Ctrl held, wheel
///     spun, button clicked — and both are correct.
///   * **Plain drag pans and plain double-click resets the camera**
///     (`pane_canvas::draw_pane`). Both are unmodified gestures, so requiring
///     Ctrl keeps them clear; the double-click case additionally needs the
///     call site to stand down, which is what [`nearest_s_band_click`] is
///     for.
///   * **Ctrl+Shift and Ctrl+Alt are refused.** BowEcho's own tests assert
///     this and it is asserted again below. Those chords are spoken for in
///     the sibling application, and a chord that means one thing in BowEcho
///     must not mean a different thing here.
///
/// On macOS `modifiers.command` is the Command key and `modifiers.ctrl` is
/// the physical Control key; on Windows and Linux egui reports `command` as a
/// mirror of `ctrl`. Accepting either means the Windows and Linux behaviour
/// is exactly `ctrl` — bit-for-bit BowEcho's rule, on the platform this
/// application ships on — while a Mac gets Command+click as well. Command is
/// admitted deliberately rather than left out: macOS routes Control+click to
/// the *secondary* button at the window-server level, so on that platform a
/// Ctrl-only rule can be swallowed before egui ever sees a primary click, and
/// Command+click is the gesture a Mac user reaches for anyway.
pub fn is_nearest_s_band_chord(modifiers: egui::Modifiers) -> bool {
    (modifiers.ctrl || modifiers.command) && !modifiers.shift && !modifiers.alt
}

/// Whether this frame's pane click is the "nearest S-band radar" gesture.
///
/// The extra arguments are the collision handling, in one place instead of
/// spread across the call sites: the gesture takes a *single* primary click
/// only.
///
/// `double_clicked` is refused, and it is worth being exact about what that
/// does and does not buy, because it is easy to claim more. egui computes
/// `Response::double_clicked` as `clicked && pointer.button_double_clicked`
/// (`egui-0.34.3/src/response.rs`), so the flag can only ever be raised on
/// the *second* release — the first release of a double-click is an ordinary
/// `clicked()` with `double_clicked()` still false. A Ctrl+double-click
/// therefore still loads a radar on the first release and still resets the
/// camera on the second; no predicate reading one frame at a time can
/// prevent that, because at the first release the second click has not
/// happened yet. What this argument does prevent is the *second* release
/// kicking a redundant second load of the same site on top of the reset,
/// which is a visible stutter in the status line and one more cancelled
/// download.
pub fn nearest_s_band_click(
    modifiers: egui::Modifiers,
    primary_clicked: bool,
    double_clicked: bool,
) -> bool {
    primary_clicked && !double_clicked && is_nearest_s_band_chord(modifiers)
}

/// Whether a click on a radar site marker may be honoured this frame.
///
/// **This is the precedence rule, and getting it backwards silently undoes
/// the whole feature.** The pane draws a marker for every catalog site and
/// hit-tests a halo of [`SITE_MARKER_HIT_POINTS`] around each one
/// (`pane_canvas::draw_radar_sites`). That halo is measured in screen
/// points, so at a wide zoom it covers a great deal of ground: at the pane's
/// own opening scale of [`STARTUP_KM_PER_POINT`] it is a
/// [`startup_marker_halo_km`] radius circle. Every TDWR this feature exists
/// to beat sits inside that circle of its downtown — Dallas 23 km, Chicago
/// 21 km, Atlanta 16 km, San Juan 8 km, all against a 36 km halo — so a call
/// site that lets a marker hit win over this gesture answers a Ctrl+click on
/// downtown Dallas with TDAL, which is exactly the complaint that produced
/// the feature.
///
/// BowEcho settles this the same way and does it in the predicate rather
/// than at the call site: `plain_map_click_allowed`
/// (`app_ui/src/main.rs:46693`) is
/// `!shift && !ctrl_best_radar_click(modifiers) && !alt_model_sounding(..)`,
/// and the marker branch is gated on it, so a held Ctrl takes the marker
/// hit-test out of the running entirely before `handle_marker_click` is
/// reached. An unmodified click still belongs to the marker: clicking KTLX's
/// box is the quickest way to load KTLX, and this gesture does not want it.
pub fn site_marker_click_allowed(modifiers: egui::Modifiers) -> bool {
    !is_nearest_s_band_chord(modifiers)
}

/// Radius in screen points within which `pane_canvas::draw_radar_sites`
/// counts a click as landing on a site marker: `SITE_MARKER_HALF` (5.0) plus
/// `SITE_CLICK_SLACK` (4.0). Restated here because those two constants are
/// private to a module this one must not depend on. The test named
/// `the_marker_halo_this_module_assumes_is_the_one_the_pane_uses` reads the
/// pane's own source and fails if either number moves.
/// Test-facing: nothing in the shipping path reads these four. They exist
/// so the assumption this module makes about the pane is written down and
/// checked, which is why they are gated rather than silenced.
#[cfg(test)]
pub const SITE_MARKER_HIT_POINTS: f64 = 9.0;

/// The scale the application opens a pane at, in kilometres per screen
/// point: `app::PLACEHOLDER_KM_PER_POINT`. Restated for the same reason, and
/// pinned by the same test.
#[cfg(test)]
pub const STARTUP_KM_PER_POINT: f64 = 4.0;

/// Ground radius of the site-marker halo at a given scale, in kilometres.
///
/// The number that makes [`site_marker_click_allowed`] necessary rather than
/// tidy: a screen-space hit radius is a large geographic one whenever the
/// pane is zoomed out.
#[cfg(test)]
pub fn marker_halo_km(km_per_point: f64) -> f64 {
    SITE_MARKER_HIT_POINTS * km_per_point
}

/// [`marker_halo_km`] at the scale the application actually opens on: 36 km.
#[cfg(test)]
pub fn startup_marker_halo_km() -> f64 {
    marker_halo_km(STARTUP_KM_PER_POINT)
}

/// The site a Ctrl+click resolved to.
#[derive(Clone, Debug, PartialEq)]
pub struct SiteChoice {
    /// Catalog id, as the catalog spells it — what `App::start_live` wants.
    pub id: String,
    pub name: Option<String>,
    /// Great-circle distance from the click to the antenna, kilometres.
    pub distance_km: f64,
    /// Height of the 0.5 degree beam centre above the antenna over the
    /// clicked point, metres. Reported, not ranked on; see the module
    /// documentation.
    pub beam_height_m: f64,
}

impl SiteChoice {
    /// The status line announcing this choice.
    ///
    /// It lives here rather than at the call site because the distance and the
    /// beam height are the evidence for the choice, and an operator who asked
    /// for the nearest S-band radar and got one 300 km away needs to see that
    /// in the same breath as the id.
    pub fn status_line(&self) -> String {
        format!(
            "{} - nearest WSR-88D, {:.0} km, 0.5 deg beam {:.1} km",
            self.id,
            self.distance_km,
            self.beam_height_m / 1000.0
        )
    }
}

/// The status line for a click with no S-band radar in range.
pub fn no_site_in_range_status() -> String {
    format!("No WSR-88D within {MAX_SITE_RANGE_KM:.0} km of that point")
}

/// Great-circle distance between two positions, in kilometres.
///
/// Haversine on the R = 6371 km sphere, in the `atan2` form that stays
/// accurate for the small separations this feature actually deals in
/// (Sinnott, R. W., 1984: Virtues of the Haversine. *Sky and Telescope*,
/// **68**(2), 159). A planar approximation is not usable here: it is the
/// `cos(latitude)` term that makes a degree of longitude at Kodiak a little
/// over half of what it is at Key West, and without it the radar nearest
/// Kodiak comes out as PAHG when it is PAKC, 66 km closer
/// (`a_planar_nearest_would_pick_the_wrong_alaskan_radar`).
///
/// A sphere here is deliberately mixed with an ellipsoid upstream, and the
/// size of that mismatch was measured rather than argued. The lat/lon the
/// application hands in comes from `map_scene::RadarProjection::
/// world_to_lon_lat`, a Vincenty direct geodesic on WGS-84; ranking it on a
/// sphere is only safe if the two never disagree about the *winner*. Over the
/// 159 S-band sites in the shipped site cache and a 0.25 degree CONUS grid
/// (24 885 clicks, 24-50 N, 66-125 W), the sphere and a WGS-84 inverse
/// geodesic choose a different radar at 47 points, 0.19 per cent: 14 of them
/// sit within a kilometre of the 460 km fence over open water or northern
/// Mexico, and at the other 33 the two candidates are within 0.86 km of each
/// other, which is a tie in every sense that matters to an analyst. Going to
/// an ellipsoid here would change which of two equidistant radars is offered
/// and nothing else, so it is not worth the second geodesic implementation.
pub fn great_circle_km(lat_a_deg: f64, lon_a_deg: f64, lat_b_deg: f64, lon_b_deg: f64) -> f64 {
    let d_lat = (lat_b_deg - lat_a_deg).to_radians();
    let d_lon = (lon_b_deg - lon_a_deg).to_radians();
    let lat_a = lat_a_deg.to_radians();
    let lat_b = lat_b_deg.to_radians();
    let chord =
        (d_lat * 0.5).sin().powi(2) + lat_a.cos() * lat_b.cos() * (d_lon * 0.5).sin().powi(2);
    2.0 * EARTH_RADIUS_KM * chord.sqrt().atan2((1.0 - chord).max(0.0).sqrt())
}

/// Height of the 0.5 degree beam centre over a point `distance_km` away
/// across the ground, in metres above the antenna.
///
/// The ground distance is inverted to a slant range first
/// (`render2d::beam::slant_range_for_ground_arc_m`) rather than being passed
/// in as if it were one, so the number is the 4/3-effective-earth geometry
/// the rest of this workspace draws with (Doviak, R. J., and D. S. Zrnic,
/// 1993: *Doppler Radar and Weather Observations*, 2nd ed., Academic Press,
/// eqs. 2.28b and 2.28c).
fn lowest_beam_height_m(distance_km: f64) -> f64 {
    let ground_m = distance_km * 1000.0;
    let slant_m =
        render2d::beam::slant_range_for_ground_arc_m(ground_m, LOWEST_TILT_DEG, MAX_SLANT_RANGE_M)
            .unwrap_or(ground_m);
    render2d::beam::beam_height_arl_m(slant_m, LOWEST_TILT_DEG)
}

/// The WSR-88D to load for a click at `latitude_deg`, `longitude_deg`.
///
/// Nearest by great-circle distance among the catalog entries that
/// [`classify_site`] admits as S-band, within [`MAX_SITE_RANGE_KM`].
/// Terminal radars and profilers never compete, which is the entire point of
/// the gesture.
///
/// `None` means no WSR-88D covers the click — an ocean click, a click in
/// central Asia, or a click made before the site directory has arrived. The
/// caller should say so rather than loading something.
///
/// Rejected without looking at the catalog: a non-finite click, and a
/// latitude outside +/-90. Skipped inside the catalog: any entry with a
/// non-finite or out-of-range position. Longitude needs no wrapping — the
/// haversine's longitude term is periodic, so a click at 190 E and a click at
/// -170 E give identical distances.
///
/// Exact distance ties break on the smaller id, so the answer does not depend
/// on the order the catalog happens to arrive in.
pub fn nearest_s_band_site(
    latitude_deg: f64,
    longitude_deg: f64,
    sites: &[LocatedSite],
) -> Option<SiteChoice> {
    if !latitude_deg.is_finite() || !longitude_deg.is_finite() || latitude_deg.abs() > 90.0 {
        return None;
    }
    let mut best: Option<(f64, &LocatedSite)> = None;
    for site in sites {
        if !classify_site(&site.id).is_s_band_nexrad() {
            continue;
        }
        if !site.latitude_deg.is_finite()
            || !site.longitude_deg.is_finite()
            || site.latitude_deg.abs() > 90.0
        {
            continue;
        }
        let distance_km = great_circle_km(
            latitude_deg,
            longitude_deg,
            site.latitude_deg,
            site.longitude_deg,
        );
        if !distance_km.is_finite() || distance_km > MAX_SITE_RANGE_KM {
            continue;
        }
        let better = match &best {
            None => true,
            Some((best_km, best_site)) => {
                distance_km < *best_km
                    || (distance_km == *best_km && site.id.as_str() < best_site.id.as_str())
            }
        };
        if better {
            best = Some((distance_km, site));
        }
    }
    let (distance_km, site) = best?;
    Some(SiteChoice {
        id: site.id.clone(),
        name: site.name.clone(),
        distance_km,
        beam_height_m: lowest_beam_height_m(distance_km),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real NWS radar-station catalog, transcribed verbatim from
    /// `https://api.weather.gov/radar/stations` on 2026-08-18: every station
    /// the feed publishes, with the position and the `stationType` it
    /// publishes. Columns are id, latitude, longitude, name, station type.
    ///
    /// It is embedded rather than fetched so the tests are hermetic and
    /// offline, and it is the whole catalog rather than a handful of rows so
    /// that "the nearest WSR-88D to downtown Dallas" is a real answer over
    /// the real network and not an artifact of which sites got listed.
    /// `the_shipped_site_cache_agrees_with_the_transcript` re-checks it
    /// against the file this application actually reads, when that file is on
    /// the machine running the tests.
    const REAL_STATION_CATALOG: &str = "\
AWPA2\t61.15\t-149.78\tAnchorage\tProfiler\n\
HWPA2\t59.65\t-151.46\tHomer\tProfiler\n\
KABR\t45.45583\t-98.41305\tAberdeen\tWSR-88D\n\
KABX\t35.14972\t-106.82388\tAlbuquerque\tWSR-88D\n\
KAKQ\t36.98388\t-77.0075\tNorfolk\tWSR-88D\n\
KAMA\t35.23333\t-101.70927\tAmarillo\tWSR-88D\n\
KAMX\t25.61055\t-80.41305\tMiami\tWSR-88D\n\
KAPX\t44.90634\t-84.71953\tNCL Michigan\tWSR-88D\n\
KARX\t43.82277\t-91.1911\tLa Crosse\tWSR-88D\n\
KATX\t48.19461\t-122.49568\tSeattle\tWSR-88D\n\
KBBX\t39.49611\t-121.63165\tBeale AFB\tWSR-88D\n\
KBGM\t42.19969\t-75.98472\tBinghamton\tWSR-88D\n\
KBHX\t40.49833\t-124.29215\tEureka (Bunker Hill)\tWSR-88D\n\
KBIS\t46.77083\t-100.76027\tBismarck\tWSR-88D\n\
KBLX\t45.85377\t-108.60679\tBillings\tWSR-88D\n\
KBMX\t33.17194\t-86.76972\tBirmingham\tWSR-88D\n\
KBOX\t41.95577\t-71.13686\tBoston\tWSR-88D\n\
KBRO\t25.91555\t-97.4186\tBrownsville\tWSR-88D\n\
KBUF\t42.9486\t-78.73694\tBuffalo\tWSR-88D\n\
KBYX\t24.59694\t-81.70333\tKey West\tWSR-88D\n\
KCAE\t33.9486\t-81.11861\tColumbia\tWSR-88D\n\
KCBW\t46.03916\t-67.80642\tCaribou\tWSR-88D\n\
KCBX\t43.49021\t-116.23602\tBoise\tWSR-88D\n\
KCCX\t40.92305\t-78.00389\tState College\tWSR-88D\n\
KCLE\t41.41305\t-81.86\tCleveland\tWSR-88D\n\
KCLX\t32.65552\t-81.04219\tCharleston,SC\tWSR-88D\n\
KCRP\t27.78388\t-97.51083\tCorpus Christi\tWSR-88D\n\
KCXX\t44.5111\t-73.16639\tBurlington\tWSR-88D\n\
KCYS\t41.15194\t-104.8061\tCheyenne\tWSR-88D\n\
KDAX\t38.50111\t-121.67782\tSacramento\tWSR-88D\n\
KDDC\t37.76083\t-99.96888\tDodge City\tWSR-88D\n\
KDFX\t29.2725\t-100.28027\tLaughlin AFB\tWSR-88D\n\
KDGX\t32.27999\t-89.98444\tJackson/Brandon,MS\tWSR-88D\n\
KDIX\t39.94694\t-74.41072\tPhiladelphia\tWSR-88D\n\
KDLH\t46.83694\t-92.20971\tDuluth\tWSR-88D\n\
KDMX\t41.7311\t-93.72285\tDes Moines\tWSR-88D\n\
KDOX\t38.82555\t-75.44\tDover AFB\tWSR-88D\n\
KDTX\t42.69999\t-83.47166\tDetroit\tWSR-88D\n\
KDVN\t41.61166\t-90.58083\tQuad Cities\tWSR-88D\n\
KDYX\t32.53833\t-99.25416\tDyess AFB\tWSR-88D\n\
KEAX\t38.81024\t-94.26446\tPleasant Hill\tWSR-88D\n\
KEMX\t31.89361\t-110.63027\tTucson\tWSR-88D\n\
KENX\t42.58655\t-74.06408\tAlbany\tWSR-88D\n\
KEOX\t31.46055\t-85.45938\tFt Rucker\tWSR-88D\n\
KEPZ\t31.87305\t-106.69799\tEl Paso\tWSR-88D\n\
KESX\t35.70111\t-114.89138\tLas Vegas\tWSR-88D\n\
KEVX\t30.56503\t-85.92166\tEglin Afb\tWSR-88D\n\
KEWX\t29.70405\t-98.0286\tAustin/San Antonio\tWSR-88D\n\
KEYX\t35.09777\t-117.56074\tEdwards AFB\tWSR-88D\n\
KFCX\t37.02416\t-80.27416\tRoanoke\tWSR-88D\n\
KFDR\t34.36219\t-98.97666\tAltus AFB\tWSR-88D\n\
KFDX\t34.63416\t-103.61888\tCannon AFB\tWSR-88D\n\
KFFC\t33.36333\t-84.56583\tAtlanta\tWSR-88D\n\
KFSD\t43.58777\t-96.72888\tSioux Falls\tWSR-88D\n\
KFSX\t34.57433\t-111.19843\tFlagstaff\tWSR-88D\n\
KFTG\t39.78663\t-104.5458\tDenver\tWSR-88D\n\
KFWS\t32.57277\t-97.30313\tDallas/Ft Worth\tWSR-88D\n\
KGGW\t48.20635\t-106.62468\tGlasgow\tWSR-88D\n\
KGJX\t39.06222\t-108.21375\tGrand Junction\tWSR-88D\n\
KGLD\t39.36694\t-101.70027\tGoodland\tWSR-88D\n\
KGRB\t44.49862\t-88.1111\tGreen Bay\tWSR-88D\n\
KGRK\t30.72166\t-97.38277\tFt Hood\tWSR-88D\n\
KGRR\t42.89388\t-85.54488\tGrand Rapids\tWSR-88D\n\
KGSP\t34.8833\t-82.21983\tGreer\tWSR-88D\n\
KGWX\t33.89691\t-88.32919\tColumbus AFB\tWSR-88D\n\
KGYX\t43.8913\t-70.25636\tPortland,ME\tWSR-88D\n\
KHDC\t30.5196\t-90.4074\tHammond\tWSR-88D\n\
KHDX\t33.07699\t-106.12002\tHolloman AFB\tWSR-88D\n\
KHGX\t29.47194\t-95.07888\tHouston\tWSR-88D\n\
KHNX\t36.31416\t-119.63213\tSan Joaquin Valley\tWSR-88D\n\
KHPX\t36.73666\t-87.28499\tFt Campbell\tWSR-88D\n\
KHTX\t34.93055\t-86.08361\tNortheast Alabama\tWSR-88D\n\
KICT\t37.65444\t-97.44305\tWichita\tWSR-88D\n\
KICX\t37.59104\t-112.86221\tCedar City\tWSR-88D\n\
KILN\t39.42027\t-83.82166\tCincinnati\tWSR-88D\n\
KILX\t40.15049\t-89.33679\tLincoln\tWSR-88D\n\
KIND\t39.70749\t-86.28027\tIndianapolis\tWSR-88D\n\
KINX\t36.17499\t-95.56413\tTulsa\tWSR-88D\n\
KIWA\t33.28916\t-111.66999\tPhoenix\tWSR-88D\n\
KIWX\t41.3586\t-85.7\tNorthern Indiana\tWSR-88D\n\
KJAX\t30.48463\t-81.7019\tJacksonville\tWSR-88D\n\
KJGX\t32.67499\t-83.35111\tRobins AFB\tWSR-88D\n\
KJKL\t37.59083\t-83.31305\tJackson,KY\tWSR-88D\n\
KLBB\t33.65413\t-101.81416\tLubbock\tWSR-88D\n\
KLCH\t30.1253\t-93.21588\tLake Charles\tWSR-88D\n\
KLGX\t47.11689\t-124.10663\tLangley Hill\tWSR-88D\n\
KLNX\t41.95794\t-100.57621\tNorth Platte\tWSR-88D\n\
KLOT\t41.60444\t-88.08444\tChicago\tWSR-88D\n\
KLRX\t40.73972\t-116.80277\tElko\tWSR-88D\n\
KLSX\t38.69888\t-90.68277\tSt Louis\tWSR-88D\n\
KLTX\t33.98916\t-78.42916\tWilmington\tWSR-88D\n\
KLVX\t37.97527\t-85.94388\tLouisville\tWSR-88D\n\
KLWX\t38.9761\t-77.4875\tSterling\tWSR-88D\n\
KLZK\t34.83638\t-92.26194\tLittle Rock\tWSR-88D\n\
KMAF\t31.94346\t-102.18924\tMidland/Odessa\tWSR-88D\n\
KMAX\t42.08111\t-122.71735\tMedford\tWSR-88D\n\
KMBX\t48.39249\t-100.86443\tMinot AFB\tWSR-88D\n\
KMHX\t34.77583\t-76.87639\tMorehead City\tWSR-88D\n\
KMKX\t42.96777\t-88.55055\tMilwaukee\tWSR-88D\n\
KMLB\t28.11305\t-80.65444\tMelbourne\tWSR-88D\n\
KMOB\t30.67944\t-88.23972\tMobile\tWSR-88D\n\
KMPX\t44.84888\t-93.56552\tMinneapolis\tWSR-88D\n\
KMQT\t46.5311\t-87.54833\tMarquette\tWSR-88D\n\
KMRX\t36.16833\t-83.40194\tKnoxville\tWSR-88D\n\
KMSX\t47.0411\t-113.9861\tMissoula\tWSR-88D\n\
KMTX\t41.26277\t-112.44777\tSalt Lake City\tWSR-88D\n\
KMUX\t37.15522\t-121.89843\tSan Francisco\tWSR-88D\n\
KMVX\t47.52805\t-97.32499\tFargo/Grand Forks\tWSR-88D\n\
KMXX\t32.53664\t-85.78975\tMaxwell AFB\tWSR-88D\n\
KNKX\t32.91888\t-117.04193\tSan Diego\tWSR-88D\n\
KNQA\t35.34472\t-89.87333\tMemphis\tWSR-88D\n\
KOAX\t41.32027\t-96.3668\tOmaha\tWSR-88D\n\
KOHX\t36.24722\t-86.5625\tNashville\tWSR-88D\n\
KOKX\t40.86552\t-72.86392\tBrookhaven\tWSR-88D\n\
KOTX\t47.68055\t-117.62582\tSpokane\tWSR-88D\n\
KPAH\t37.06833\t-88.77194\tPaducah\tWSR-88D\n\
KPBZ\t40.53166\t-80.21794\tPittsburgh\tWSR-88D\n\
KPDT\t45.69055\t-118.8529\tPendleton\tWSR-88D\n\
KPOE\t31.15527\t-92.97583\tFt Polk\tWSR-88D\n\
KPUX\t38.45944\t-104.18138\tPueblo\tWSR-88D\n\
KRAX\t35.66527\t-78.49\tRaleigh/Durham\tWSR-88D\n\
KRGX\t39.75405\t-119.46202\tReno\tWSR-88D\n\
KRIW\t43.0661\t-108.47729\tRiverton/Lander\tWSR-88D\n\
KRLX\t38.3111\t-81.72277\tCharleston,WV\tWSR-88D\n\
KRTX\t45.71499\t-122.96499\tPortland,OR\tWSR-88D\n\
KSFX\t43.10559\t-112.68612\tPocatello\tWSR-88D\n\
KSGF\t37.23527\t-93.40027\tSpringfield\tWSR-88D\n\
KSHV\t32.45083\t-93.84124\tShreveport\tWSR-88D\n\
KSJT\t31.37111\t-100.49221\tSan Angelo\tWSR-88D\n\
KSOX\t33.81773\t-117.63599\tSanta Ana Mts\tWSR-88D\n\
KSRX\t35.29041\t-94.36188\tWestern Arkansas\tWSR-88D\n\
KTBW\t27.70527\t-82.40194\tTampa\tWSR-88D\n\
KTFX\t47.45972\t-111.38527\tGreat Falls\tWSR-88D\n\
KTLH\t30.39749\t-84.32889\tTallahassee\tWSR-88D\n\
KTLX\t35.33305\t-97.27775\tNorman\tWSR-88D\n\
KTWX\t38.99694\t-96.23249\tTopeka\tWSR-88D\n\
KTYX\t43.75582\t-75.68\tFt Drum\tWSR-88D\n\
KUDX\t44.12471\t-102.82999\tRapid City\tWSR-88D\n\
KUEX\t40.32083\t-98.44194\tGrand Island\tWSR-88D\n\
KVAX\t30.89027\t-83.0018\tMoody AFB\tWSR-88D\n\
KVBX\t34.83855\t-120.3979\tVandenberg AFB\tWSR-88D\n\
KVNX\t36.74083\t-98.12749\tVance AFB\tWSR-88D\n\
KVTX\t34.41166\t-119.1786\tLos Angeles\tWSR-88D\n\
KVWX\t38.26024\t-87.72452\tEvansville,IN\tWSR-88D\n\
KYUX\t32.49527\t-114.65668\tYuma\tWSR-88D\n\
PABC\t60.79194\t-161.87637\tBethel\tWSR-88D\n\
PACG\t56.85277\t-135.52915\tSitka\tWSR-88D\n\
PAEC\t64.51139\t-165.29498\tNome\tWSR-88D\n\
PAHG\t60.72591\t-151.35144\tKenai\tWSR-88D\n\
PAIH\t59.46194\t-146.30109\tMiddleton Island\tWSR-88D\n\
PAKC\t58.67944\t-156.62942\tKing Salmon\tWSR-88D\n\
PAPD\t65.03511\t-147.5014\tFairbanks Faa\tWSR-88D\n\
PGUA\t13.45583\t144.81112\tAndersen AFB\tWSR-88D\n\
PHKI\t21.89389\t-159.55249\tSouth Kauai\tWSR-88D\n\
PHKM\t20.12527\t-155.77776\tKamuela/Kohala Apt\tWSR-88D\n\
PHMO\t21.13277\t-157.18026\tMolokai\tWSR-88D\n\
PHWA\t19.095\t-155.56887\tSouth Shore\tWSR-88D\n\
RKJK\t35.92417\t126.62222\tKunsan AB\tWSR-88D\n\
RKSG\t37.20757\t127.28556\tCamp Humphreys\tWSR-88D\n\
ROCO2\t35.23\t-97.45\tNorman\tProfiler\n\
RODN\t26.30194\t127.90972\tKadena AB\tWSR-88D\n\
TADW\t38.695\t-76.845\tAndrews Air Force Base\tTDWR\n\
TATL\t33.647\t-84.262\tAtlanta\tTDWR\n\
TBNA\t35.98\t-86.662\tNashville\tTDWR\n\
TBOS\t42.158\t-70.933\tBoston\tTDWR\n\
TBWI\t39.09\t-76.63\tBaltimore/Wash\tTDWR\n\
TCLT\t35.337\t-80.885\tCharlotte\tTDWR\n\
TCMH\t40.006\t-82.715\tColumbus,OH\tTDWR\n\
TCVG\t38.898\t-84.58\tCovington\tTDWR\n\
TDAL\t32.926\t-96.968\tDallas Love Field\tTDWR\n\
TDAY\t40.022\t-84.123\tDayton\tTDWR\n\
TDCA\t38.759\t-76.962\tWashington National\tTDWR\n\
TDEN\t39.728\t-104.526\tDenver\tTDWR\n\
TDFW\t33.065\t-96.918\tDallas/Ft. Worth\tTDWR\n\
TDJT\t26.688\t-80.273\tTrump International\tTDWR\n\
TDTW\t42.111\t-83.515\tDetroit\tTDWR\n\
TEWR\t40.593\t-74.27\tNewark\tTDWR\n\
TFLL\t26.143\t-80.344\tFort Lauderdale\tTDWR\n\
THOU\t29.516\t-95.242\tHouston Hobby\tTDWR\n\
TIAD\t39.084\t-77.529\tDulles\tTDWR\n\
TIAH\t30.065\t-95.567\tHouston International\tTDWR\n\
TICH\t37.507\t-97.437\tWitchita\tTDWR\n\
TIDS\t39.637\t-86.436\tIndianapolis\tTDWR\n\
TJFK\t40.589\t-73.881\tNew York City\tTDWR\n\
TJUA\t18.11566\t-66.07817\tSan Juan\tWSR-88D\n\
TLAS\t36.144\t-115.007\tLas Vegas\tTDWR\n\
TLKA2\t62.31\t-150.42\tTalkeetna\tProfiler\n\
TLVE\t41.29\t-82.008\tCleveland,OH\tTDWR\n\
TMCI\t39.498\t-94.742\tKansas City\tTDWR\n\
TMCO\t28.344\t-81.326\tOrlando International\tTDWR\n\
TMDW\t41.651\t-87.73\tChicago Midway\tTDWR\n\
TMEM\t34.896\t-89.993\tMemphis\tTDWR\n\
TMIA\t25.758\t-80.491\tMiami\tTDWR\n\
TMKE\t42.819\t-88.046\tMilwaukee\tTDWR\n\
TMSP\t44.871\t-92.933\tMinneapolis\tTDWR\n\
TMSY\t30.022\t-90.403\tNew Orleans\tTDWR\n\
TOKC\t35.276\t-97.51\tOklahoma City\tTDWR\n\
TORD\t41.797\t-87.858\tChicago O'Hare\tTDWR\n\
TPHL\t39.949\t-75.069\tPhiladelphia\tTDWR\n\
TPHX\t33.421\t-112.163\tPhoenix\tTDWR\n\
TPIT\t40.501\t-80.486\tPittsburgh\tTDWR\n\
TRDU\t36.002\t-78.697\tRaleigh Durham\tTDWR\n\
TSDF\t38.046\t-85.61\tLouisville,KY\tTDWR\n\
TSJU\t18.474\t-66.179\tSan Juan\tTDWR\n\
TSLC\t40.967\t-111.93\tSalt Lake City\tTDWR\n\
TSTL\t38.805\t-90.489\tSt. Louis\tTDWR\n\
TTPA\t27.86\t-82.518\tTampa Bay\tTDWR\n\
TTUL\t36.071\t-95.827\tTulsa\tTDWR\n\
";

    struct CatalogRow {
        site: LocatedSite,
        station_type: &'static str,
    }

    fn real_catalog() -> Vec<CatalogRow> {
        REAL_STATION_CATALOG
            .lines()
            .filter(|line| !line.trim().is_empty())
            .map(|line| {
                let mut fields = line.split('\t');
                let id = fields.next().expect("id column");
                let latitude_deg = fields.next().expect("latitude column");
                let longitude_deg = fields.next().expect("longitude column");
                let name = fields.next().expect("name column");
                let station_type = fields.next().expect("station type column");
                CatalogRow {
                    site: LocatedSite {
                        id: id.to_owned(),
                        name: Some(name.to_owned()),
                        latitude_deg: latitude_deg.parse().expect("latitude parses"),
                        longitude_deg: longitude_deg.parse().expect("longitude parses"),
                    },
                    station_type,
                }
            })
            .collect()
    }

    fn real_sites() -> Vec<LocatedSite> {
        real_catalog().into_iter().map(|row| row.site).collect()
    }

    fn site_named(sites: &[LocatedSite], id: &str) -> LocatedSite {
        sites
            .iter()
            .find(|site| site.id == id)
            .unwrap_or_else(|| panic!("{id} is not in the real station catalog"))
            .clone()
    }

    fn distance_to(sites: &[LocatedSite], id: &str, lat: f64, lon: f64) -> f64 {
        let site = site_named(sites, id);
        great_circle_km(lat, lon, site.latitude_deg, site.longitude_deg)
    }

    fn ctrl() -> egui::Modifiers {
        egui::Modifiers {
            ctrl: true,
            command: true,
            ..Default::default()
        }
    }

    #[test]
    fn the_transcript_has_the_shape_the_feed_published() {
        let rows = real_catalog();
        assert_eq!(rows.len(), 208, "the 2026-08-18 feed had 208 stations");
        let count = |wanted: &str| rows.iter().filter(|row| row.station_type == wanted).count();
        assert_eq!(count("WSR-88D"), 159);
        assert_eq!(count("TDWR"), 45);
        assert_eq!(count("Profiler"), 4);
    }

    /// The transcription of `stationType` into [`TDWR_SITE_IDS`] and
    /// [`PROFILER_SITE_IDS`] is pinned here: replay every station the feed
    /// published through the classifier and require the same answer.
    #[test]
    fn classification_agrees_with_the_published_station_type() {
        for row in real_catalog() {
            let expected = match row.station_type {
                "WSR-88D" => SiteClass::Wsr88d,
                "TDWR" => SiteClass::Tdwr,
                "Profiler" => SiteClass::Other,
                other => panic!("unhandled published station type {other}"),
            };
            assert_eq!(
                classify_site(&row.site.id),
                expected,
                "{} is published as {}",
                row.site.id,
                row.station_type
            );
        }
    }

    /// The two rows a prefix rule gets wrong, called out on their own so a
    /// regression names itself.
    #[test]
    fn a_prefix_rule_would_get_these_two_wrong() {
        // San Juan's S-band radar. A 'T'-prefix rule would drop Puerto Rico.
        assert_eq!(classify_site("TJUA"), SiteClass::Wsr88d);
        assert_eq!(classify_site("TSJU"), SiteClass::Tdwr);
        // Talkeetna is a wind profiler, which BowEcho's seeded table calls a
        // TDWR. Either way it loses; the label is what differs.
        assert_eq!(classify_site("TLKA2"), SiteClass::Other);
        assert_eq!(classify_site("ROCO2"), SiteClass::Other);
    }

    #[test]
    fn classification_is_case_and_whitespace_insensitive() {
        assert_eq!(classify_site(" ktlx "), SiteClass::Wsr88d);
        assert_eq!(classify_site("tdfw"), SiteClass::Tdwr);
        assert_eq!(classify_site("tjua"), SiteClass::Wsr88d);
    }

    /// An id the tables have not seen must fail toward "not S-band" unless it
    /// has the shape every new WSR-88D has.
    #[test]
    fn unknown_ids_fail_safe() {
        // KHDC (Hammond, LA) is the most recent addition to the network and
        // it is in the tables' catalog; a hypothetical successor is not.
        assert_eq!(classify_site("KHDC"), SiteClass::Wsr88d);
        assert_eq!(classify_site("KZZZ"), SiteClass::Wsr88d);
        // Unrecognised terminal-looking id: loses.
        assert_eq!(classify_site("TZZZ"), SiteClass::Tdwr);
        // Not a NEXRAD-shaped id at all: loses.
        assert_eq!(classify_site("ABCD1"), SiteClass::Other);
        assert_eq!(classify_site("KTL"), SiteClass::Other);
        assert_eq!(classify_site(""), SiteClass::Other);
        assert_eq!(classify_site("   "), SiteClass::Other);
    }

    /// What the two id tables are actually worth today: nothing, over the
    /// published catalog. Recorded so the module is not read as resting on
    /// them.
    ///
    /// Reverting either table one at a time leaves all 27 tests passing,
    /// because every published TDWR has a four-character `T` id and all four
    /// profilers have five-character ids, so the structural fallback lands
    /// them anyway. This says that in the assertion rather than leaving it to
    /// be rediscovered: the thing keeping TDAL out of Dallas is the `'T'`
    /// prefix rule plus the one TJUA exception.
    #[test]
    fn the_structural_rule_alone_already_classifies_the_published_catalog() {
        fn structural_only(id: &str) -> SiteClass {
            let id = id.trim().to_ascii_uppercase();
            if id == S_BAND_WITH_A_TERMINAL_PREFIX {
                return SiteClass::Wsr88d;
            }
            let bytes = id.as_bytes();
            if bytes.len() != 4 || !bytes.iter().all(u8::is_ascii_alphanumeric) {
                return SiteClass::Other;
            }
            if bytes[0] == b'T' {
                SiteClass::Tdwr
            } else {
                SiteClass::Wsr88d
            }
        }
        let rows = real_catalog();
        let mut terminals = 0_usize;
        for row in &rows {
            let structural = structural_only(&row.site.id);
            assert_eq!(
                structural,
                classify_site(&row.site.id),
                "{} ({}): the tables and the structural rule must agree, or one \
                 of the two is the thing actually deciding",
                row.site.id,
                row.station_type
            );
            if row.station_type == "TDWR" {
                terminals += 1;
                assert!(!structural.is_s_band_nexrad(), "{}", row.site.id);
            }
        }
        assert_eq!(terminals, 45);
        println!(
            "the structural rule alone classifies all {} published stations correctly; \
             the id tables change no present answer",
            rows.len()
        );
    }

    /// The failure the tables *can* cause, fenced off.
    ///
    /// Being inert today, the tables cannot be pinned as load-bearing — there
    /// is no published id whose answer depends on them, so no honest test can
    /// make deleting one fail. What they can still do is harm: one typo that
    /// drops a WSR-88D id into [`TDWR_SITE_IDS`] silently removes that radar
    /// from the gesture, and "Dallas has no radar" is a much quieter failure
    /// than "Dallas loads the wrong one". `KFWS` for `TFWS` is a single
    /// keystroke. So: nothing the feed publishes as a WSR-88D may appear in
    /// either exclusion table, and every id in them must lose.
    #[test]
    fn no_exclusion_table_entry_is_a_published_wsr88d() {
        let published = real_catalog();
        for id in TDWR_SITE_IDS.iter().chain(PROFILER_SITE_IDS) {
            assert!(!classify_site(id).is_s_band_nexrad(), "{id}");
            if let Some(row) = published.iter().find(|row| row.site.id == **id) {
                assert_ne!(
                    row.station_type, "WSR-88D",
                    "{id} is published as a WSR-88D and must not be in an exclusion table"
                );
            }
        }
        // The converse for the ids the proof cases turn on: still S-band.
        for id in ["KFWS", "KLOT", "KFFC", "TJUA", "KTLX", "KHDC"] {
            assert!(
                classify_site(id).is_s_band_nexrad(),
                "{id} must stay loadable"
            );
            assert!(!TDWR_SITE_IDS.contains(&id), "{id}");
            assert!(!PROFILER_SITE_IDS.contains(&id), "{id}");
        }
    }

    /// Confirm the terminal radars the proof cases lean on really are in this
    /// catalog before any assertion relies on them — and record that "TCHI",
    /// the id the request named for Chicago, does not exist. Chicago has two
    /// TDWRs, TORD and TMDW.
    #[test]
    fn the_terminal_radars_these_tests_rely_on_exist() {
        let sites = real_sites();
        for id in ["TDAL", "TDFW", "TORD", "TMDW", "TATL", "TSJU"] {
            let site = site_named(&sites, id);
            assert_eq!(classify_site(&site.id), SiteClass::Tdwr, "{id}");
        }
        assert!(
            !sites.iter().any(|site| site.id == "TCHI"),
            "TCHI is not a station; Chicago's terminal radars are TORD and TMDW"
        );
    }

    /// The ask, on real coordinates: at three downtowns a TDWR is genuinely
    /// the closest radar, and the WSR-88D must win anyway. Distances to both
    /// are printed so the assertion is legible in the test log.
    #[test]
    fn a_downtown_click_loads_the_wsr88d_not_the_closer_terminal_radar() {
        let sites = real_sites();
        // Real city-centre coordinates: Dallas City Hall, the Chicago Loop,
        // and downtown Atlanta.
        let cases = [
            ("Dallas", 32.7767, -96.7970, "TDAL", "KFWS"),
            ("Chicago", 41.8781, -87.6298, "TORD", "KLOT"),
            ("Atlanta", 33.7490, -84.3880, "TATL", "KFFC"),
        ];
        for (city, lat, lon, terminal_id, s_band_id) in cases {
            let terminal_km = distance_to(&sites, terminal_id, lat, lon);
            let s_band_km = distance_to(&sites, s_band_id, lat, lon);
            let choice = nearest_s_band_site(lat, lon, &sites)
                .unwrap_or_else(|| panic!("{city} must resolve to a WSR-88D"));
            println!(
                "{city} ({lat:.4}, {lon:.4}): {terminal_id} (TDWR) {terminal_km:.2} km, \
                 {s_band_id} (WSR-88D) {s_band_km:.2} km -> chose {} at {:.2} km, \
                 0.5 deg beam {:.0} m",
                choice.id, choice.distance_km, choice.beam_height_m
            );
            assert!(
                terminal_km < s_band_km,
                "{city}: this case is only meaningful while {terminal_id} is closer \
                 than {s_band_id} ({terminal_km:.2} km vs {s_band_km:.2} km)"
            );
            assert_eq!(choice.id, s_band_id, "{city} must load the S-band radar");
            assert!((choice.distance_km - s_band_km).abs() < 1.0e-9);
            assert!(choice.beam_height_m > 0.0);
        }
    }

    /// The case that a `'T'`-prefix rule would answer "no radar": in San Juan
    /// the terminal radar TSJU is five times closer than the WSR-88D, and the
    /// WSR-88D is itself T-prefixed.
    #[test]
    fn san_juan_keeps_its_s_band_radar_despite_the_terminal_prefix() {
        let sites = real_sites();
        let lat = 18.4655;
        let lon = -66.1057;
        let terminal_km = distance_to(&sites, "TSJU", lat, lon);
        let s_band_km = distance_to(&sites, "TJUA", lat, lon);
        let choice = nearest_s_band_site(lat, lon, &sites).expect("San Juan is covered");
        println!(
            "San Juan ({lat:.4}, {lon:.4}): TSJU (TDWR) {terminal_km:.2} km, \
             TJUA (WSR-88D) {s_band_km:.2} km -> chose {} at {:.2} km",
            choice.id, choice.distance_km
        );
        assert!(terminal_km < s_band_km);
        assert_eq!(choice.id, "TJUA");
    }

    /// Every station within reach of these clicks is a terminal radar or a
    /// profiler except one, and the ranking has to find that one.
    #[test]
    fn the_pick_is_the_nearest_s_band_site_at_a_spread_of_real_places() {
        let sites = real_sites();
        let cases = [
            ("Houston", 29.7604, -95.3698, "KHGX"),
            ("Las Vegas", 36.1699, -115.1398, "KESX"),
            ("Denver", 39.7392, -104.9903, "KFTG"),
            ("Minneapolis", 44.9778, -93.2650, "KMPX"),
            ("Norman OK", 35.2226, -97.4395, "KTLX"),
            ("Anchorage", 61.2181, -149.9003, "PAHG"),
            ("Honolulu", 21.3069, -157.8583, "PHMO"),
        ];
        for (place, lat, lon, expected) in cases {
            let choice = nearest_s_band_site(lat, lon, &sites)
                .unwrap_or_else(|| panic!("{place} must resolve to a WSR-88D"));
            println!(
                "{place}: chose {} at {:.2} km, 0.5 deg beam {:.0} m",
                choice.id, choice.distance_km, choice.beam_height_m
            );
            assert_eq!(choice.id, expected, "{place}");
            assert!(choice.distance_km <= MAX_SITE_RANGE_KM);
        }
    }

    /// Kodiak, Alaska is why the distance has to be a great circle. At 57.8 N
    /// a degree of longitude is a little over half a degree of latitude, so a
    /// nearest computed on raw degrees as if they were a plane answers PAHG
    /// (Kenai) when the radar that actually covers Kodiak is PAKC (King
    /// Salmon), 66 km closer. Both are inside the fence, so this is the
    /// projection being wrong and nothing else.
    #[test]
    fn a_planar_nearest_would_pick_the_wrong_alaskan_radar() {
        let sites = real_sites();
        let lat = 57.7900;
        let lon = -152.4072;
        let planar = sites
            .iter()
            .filter(|site| classify_site(&site.id).is_s_band_nexrad())
            .min_by(|left, right| {
                let degrees =
                    |site: &LocatedSite| (site.latitude_deg - lat).hypot(site.longitude_deg - lon);
                degrees(left).total_cmp(&degrees(right))
            })
            .expect("Alaska has WSR-88Ds")
            .clone();
        let planar_km = distance_to(&sites, &planar.id, lat, lon);
        let choice = nearest_s_band_site(lat, lon, &sites).expect("Kodiak is covered");
        println!(
            "Kodiak: great circle chose {} at {:.2} km; degrees-as-plane chose {} \
             at {:.2} km",
            choice.id, choice.distance_km, planar.id, planar_km
        );
        assert_eq!(choice.id, "PAKC");
        assert_eq!(planar.id, "PAHG");
        assert!(
            planar_km > choice.distance_km + 50.0,
            "the planar answer is supposed to be substantially worse"
        );
    }

    #[test]
    fn an_ocean_click_far_from_every_radar_resolves_to_nothing() {
        let sites = real_sites();
        // Mid North Pacific, ~900 km from the nearest Hawaiian radar.
        assert_eq!(nearest_s_band_site(30.0, -160.0, &sites), None);
        // Southern Indian Ocean: nothing in this catalog is even close.
        assert_eq!(nearest_s_band_site(-45.0, 90.0, &sites), None);
    }

    #[test]
    fn a_click_just_inside_and_just_outside_the_fence_answers_differently() {
        let sites = real_sites();
        let ktlx = site_named(&sites, "KTLX");
        let only_ktlx = vec![ktlx.clone()];
        // Due north of KTLX. One degree of latitude is 111.19 km on this
        // sphere, so 4.1 degrees is inside the fence and 4.2 is outside.
        let inside = nearest_s_band_site(ktlx.latitude_deg + 4.1, ktlx.longitude_deg, &only_ktlx);
        let outside = nearest_s_band_site(ktlx.latitude_deg + 4.2, ktlx.longitude_deg, &only_ktlx);
        let inside = inside.expect("4.1 degrees north of KTLX is inside 460 km");
        println!(
            "fence: {:.2} km accepted, {:.2} km refused",
            inside.distance_km,
            great_circle_km(
                ktlx.latitude_deg + 4.2,
                ktlx.longitude_deg,
                ktlx.latitude_deg,
                ktlx.longitude_deg
            )
        );
        assert!(inside.distance_km <= MAX_SITE_RANGE_KM);
        assert_eq!(outside, None);
    }

    #[test]
    fn an_empty_or_terminal_only_catalog_resolves_to_nothing() {
        assert_eq!(nearest_s_band_site(32.7767, -96.7970, &[]), None);
        let sites = real_sites();
        let terminals = sites
            .iter()
            .filter(|site| classify_site(&site.id) == SiteClass::Tdwr)
            .cloned()
            .collect::<Vec<_>>();
        assert!(terminals.len() >= 40);
        assert_eq!(nearest_s_band_site(32.7767, -96.7970, &terminals), None);
    }

    #[test]
    fn a_non_finite_click_is_refused_rather_than_ranked() {
        let sites = real_sites();
        for (lat, lon) in [
            (f64::NAN, -97.0),
            (35.0, f64::NAN),
            (f64::INFINITY, -97.0),
            (35.0, f64::NEG_INFINITY),
            (91.0, -97.0),
            (-90.5, -97.0),
        ] {
            assert_eq!(nearest_s_band_site(lat, lon, &sites), None, "{lat} {lon}");
        }
    }

    /// The out-of-range *latitude* half of that guard, pinned so it cannot be
    /// deleted quietly.
    ///
    /// The real catalog cannot pin it: over the real station list every
    /// latitude past the pole is thousands of kilometres from every radar, so
    /// the 460 km fence refuses the click whether the guard is there or not,
    /// and the assertion above passes with the guard removed (verified by
    /// reverting it). This is a degenerate arrangement built to make the
    /// guard the only thing that answers - one site just short of the pole,
    /// one click just past it, 55 km apart - so removing the guard turns the
    /// `None` into a site.
    #[test]
    fn a_latitude_past_the_pole_is_refused_even_with_a_site_in_reach() {
        let polar = vec![LocatedSite {
            id: "KPOL".to_owned(),
            name: Some("a site near the pole".to_owned()),
            latitude_deg: 89.5,
            longitude_deg: 0.0,
        }];
        let reachable = great_circle_km(90.0, 0.0, 89.5, 0.0);
        assert!(
            reachable < MAX_SITE_RANGE_KM,
            "the arrangement must put the site inside the fence, it is {reachable:.1} km"
        );
        assert!(nearest_s_band_site(89.5, 0.0, &polar).is_some());
        for latitude in [90.000_001, 90.5, 100.0, -90.5] {
            assert_eq!(
                nearest_s_band_site(latitude, 0.0, &polar),
                None,
                "latitude {latitude} is not a place"
            );
        }
    }

    #[test]
    fn catalog_entries_with_impossible_positions_are_skipped_not_fatal() {
        let mut sites = real_sites();
        sites.insert(
            0,
            LocatedSite {
                id: "KBAD".to_owned(),
                name: Some("broken row".to_owned()),
                latitude_deg: f64::NAN,
                longitude_deg: -96.8,
            },
        );
        sites.insert(
            1,
            LocatedSite {
                id: "KAAA".to_owned(),
                name: Some("impossible latitude".to_owned()),
                latitude_deg: 1000.0,
                longitude_deg: -96.8,
            },
        );
        let choice = nearest_s_band_site(32.7767, -96.7970, &sites).expect("Dallas is covered");
        assert_eq!(choice.id, "KFWS");
    }

    /// The same guard on the catalog side, pinned the same way and for the
    /// same reason.
    ///
    /// The test above does not pin it: a `NaN` row produces a `NaN` distance
    /// that the finite check on the distance already drops, and a row at
    /// latitude 1000 comes out 12 554 km from Dallas, which the fence already
    /// drops. Both survive the guard being reverted. A row whose latitude is
    /// only just past the pole does not - it lands 56 km from this click and
    /// would win outright - so this is the arrangement that fails when the
    /// guard goes.
    #[test]
    fn a_catalog_row_past_the_pole_cannot_win_a_click_beside_it() {
        let sites = vec![
            LocatedSite {
                id: "KZZZ".to_owned(),
                name: Some("row past the pole".to_owned()),
                latitude_deg: 90.5,
                longitude_deg: 0.0,
            },
            LocatedSite {
                id: "KFAR".to_owned(),
                name: Some("a real position, further off".to_owned()),
                latitude_deg: 87.0,
                longitude_deg: 0.0,
            },
        ];
        let would_be_km = great_circle_km(89.99, 0.0, 90.5, 0.0);
        assert!(
            would_be_km < MAX_SITE_RANGE_KM,
            "the bad row has to be inside the fence for this to prove anything, \
             it is {would_be_km:.1} km"
        );
        let choice = nearest_s_band_site(89.99, 0.0, &sites);
        assert_eq!(
            choice.map(|choice| choice.id),
            Some("KFAR".to_owned()),
            "the row past the pole must be skipped, not ranked"
        );
    }

    /// The answer must not depend on the order the catalog arrived in. The
    /// site directory is delivered by a worker thread and merged from a disk
    /// cache and a network fetch, so its order is not something to rely on.
    #[test]
    fn the_pick_does_not_depend_on_catalog_order() {
        let sites = real_sites();
        let mut reversed = sites.clone();
        reversed.reverse();
        for (lat, lon) in [
            (32.7767, -96.7970),
            (41.8781, -87.6298),
            (33.7490, -84.3880),
            (18.4655, -66.1057),
            (61.2181, -149.9003),
        ] {
            assert_eq!(
                nearest_s_band_site(lat, lon, &sites),
                nearest_s_band_site(lat, lon, &reversed),
                "{lat} {lon}"
            );
        }
    }

    /// The tie-break itself, which the test above does not reach.
    ///
    /// No two real antennas share an `f64` position, so reversing the real
    /// catalog exercises no tie at all and that test passes with the
    /// tie-break deleted (verified by reverting it). An exact tie has to be
    /// built: a second row carrying a real site's coordinates verbatim under
    /// a different id. Both orders must then answer the same thing, and the
    /// answer must be the smaller id rather than whichever row came first.
    #[test]
    fn an_exact_tie_breaks_on_the_id_and_not_on_the_arrival_order() {
        let sites = real_sites();
        let kfws = site_named(&sites, "KFWS");
        let twin = LocatedSite {
            id: "KAAA".to_owned(),
            name: Some("same antenna position, smaller id".to_owned()),
            ..kfws.clone()
        };
        assert_eq!(twin.latitude_deg, kfws.latitude_deg);
        assert_eq!(twin.longitude_deg, kfws.longitude_deg);
        assert!(classify_site(&twin.id).is_s_band_nexrad());

        let (lat, lon) = (32.7767, -96.7970);
        let kfws_first = vec![kfws.clone(), twin.clone()];
        let twin_first = vec![twin, kfws];
        let a = nearest_s_band_site(lat, lon, &kfws_first).expect("a tie still resolves");
        let b = nearest_s_band_site(lat, lon, &twin_first).expect("a tie still resolves");
        assert_eq!(a.distance_km, b.distance_km, "the tie has to be exact");
        assert_eq!(
            a.id, "KAAA",
            "the smaller id wins, whichever row came first"
        );
        assert_eq!(a, b);
    }

    /// Longitude is not wrapped anywhere in this module because it does not
    /// need to be; this is that claim, checked.
    #[test]
    fn a_longitude_written_outside_the_usual_range_gives_the_same_answer() {
        let sites = real_sites();
        let here = nearest_s_band_site(32.7767, -96.7970, &sites);
        let wrapped = nearest_s_band_site(32.7767, -96.7970 + 360.0, &sites);
        assert!(here.is_some());
        assert_eq!(
            here.as_ref().map(|choice| choice.id.as_str()),
            wrapped.as_ref().map(|choice| choice.id.as_str())
        );
    }

    #[test]
    fn the_beam_height_is_the_four_thirds_earth_geometry_this_workspace_draws_with() {
        // Zero range puts the beam centre at the antenna.
        assert!(lowest_beam_height_m(0.0).abs() < 1.0e-6);
        // Monotone in range, which is why ranking on distance and ranking on
        // beam height are the same ranking.
        let mut previous = -1.0;
        for distance_km in [0.0, 10.0, 50.0, 100.0, 230.0, 460.0] {
            let height = lowest_beam_height_m(distance_km);
            assert!(height > previous, "beam height must increase with range");
            previous = height;
        }
        // At 100 km on the 0.5 degree cut the 4/3-earth beam centre is about
        // 1.46 km up: 873 m of tilt (100 km times sin 0.5 deg) plus 589 m of
        // curvature (r squared over twice the 8495 km effective earth).
        let at_100_km = lowest_beam_height_m(100.0);
        assert!(
            (1400.0..1520.0).contains(&at_100_km),
            "0.5 deg beam at 100 km was {at_100_km} m"
        );
    }

    #[test]
    fn the_great_circle_distance_matches_known_separations() {
        // Zero distance to itself.
        assert!(great_circle_km(35.3331, -97.2778, 35.3331, -97.2778) < 1.0e-9);
        // One degree of latitude on the R = 6371 km sphere is 111.19 km.
        let one_degree = great_circle_km(35.0, -97.0, 36.0, -97.0);
        assert!((one_degree - 111.19).abs() < 0.02, "{one_degree}");
        // A degree of longitude shrinks with the cosine of the latitude: at
        // 60 N it is half what it is at the equator.
        let at_equator = great_circle_km(0.0, 0.0, 0.0, 1.0);
        let at_sixty = great_circle_km(60.0, 0.0, 60.0, 1.0);
        assert!((at_sixty / at_equator - 0.5).abs() < 0.001);
        // Symmetric.
        let sites = real_sites();
        let a = site_named(&sites, "KTLX");
        let b = site_named(&sites, "KFWS");
        let forward = great_circle_km(
            a.latitude_deg,
            a.longitude_deg,
            b.latitude_deg,
            b.longitude_deg,
        );
        let backward = great_circle_km(
            b.latitude_deg,
            b.longitude_deg,
            a.latitude_deg,
            a.longitude_deg,
        );
        assert!((forward - backward).abs() < 1.0e-9);
        println!("KTLX to KFWS is {forward:.2} km");
        assert!((300.0..315.0).contains(&forward), "{forward}");
    }

    // ---- the gesture ----

    #[test]
    fn ctrl_alone_is_the_gesture() {
        assert!(is_nearest_s_band_chord(ctrl()));
        assert!(nearest_s_band_click(ctrl(), true, false));
    }

    #[test]
    fn an_unmodified_click_is_not_the_gesture() {
        let none = egui::Modifiers::default();
        assert!(!is_nearest_s_band_chord(none));
        assert!(!nearest_s_band_click(none, true, false));
    }

    /// BowEcho asserts exactly this about its own predicate, and the two
    /// applications must not disagree about what a chord means.
    #[test]
    fn ctrl_shift_and_ctrl_alt_are_refused() {
        let ctrl_shift = egui::Modifiers {
            ctrl: true,
            command: true,
            shift: true,
            ..Default::default()
        };
        let ctrl_alt = egui::Modifiers {
            ctrl: true,
            command: true,
            alt: true,
            ..Default::default()
        };
        let ctrl_alt_shift = egui::Modifiers {
            ctrl: true,
            command: true,
            alt: true,
            shift: true,
            ..Default::default()
        };
        for modifiers in [ctrl_shift, ctrl_alt, ctrl_alt_shift] {
            assert!(!is_nearest_s_band_chord(modifiers));
            assert!(!nearest_s_band_click(modifiers, true, false));
        }
        // Shift and Alt on their own are somebody else's, too.
        for modifiers in [
            egui::Modifiers {
                shift: true,
                ..Default::default()
            },
            egui::Modifiers {
                alt: true,
                ..Default::default()
            },
        ] {
            assert!(!is_nearest_s_band_chord(modifiers));
        }
    }

    /// egui's `COMMAND` is Ctrl on Windows and Linux and Command on macOS.
    /// Both are accepted; the Windows behaviour is therefore exactly `ctrl`.
    #[test]
    fn the_platform_command_key_is_accepted_as_well() {
        assert!(is_nearest_s_band_chord(egui::Modifiers::COMMAND));
        assert!(is_nearest_s_band_chord(egui::Modifiers::CTRL));
        // A macOS Command+click, as egui reports it.
        let mac_command = egui::Modifiers {
            command: true,
            mac_cmd: true,
            ..Default::default()
        };
        assert!(is_nearest_s_band_chord(mac_command));
    }

    /// The camera reset owns the double-click, so the gesture stands down for
    /// one. Nothing else about the pane's existing gestures is modifier-based,
    /// so nothing else can collide: the pan is an unmodified drag, and the
    /// zoom is a wheel event rather than a click.
    #[test]
    fn a_double_click_stays_the_camera_reset() {
        assert!(!nearest_s_band_click(ctrl(), true, true));
        assert!(!nearest_s_band_click(ctrl(), false, false));
    }

    /// Ctrl+scroll zooms the pane. That is a `MouseWheel` event and this is a
    /// pointer click, so holding Ctrl to zoom and then clicking is two
    /// gestures, not one ambiguous one — and this predicate says yes to the
    /// click either way.
    #[test]
    fn holding_ctrl_for_the_zoom_does_not_stop_a_ctrl_click() {
        assert!(nearest_s_band_click(ctrl(), true, false));
    }

    /// A Ctrl+double-click, stated as it actually behaves rather than as it
    /// would be convenient to describe it.
    ///
    /// egui raises `double_clicked` only together with `clicked`, and only on
    /// the second release, so the frames a Ctrl+double-click produces are
    /// `(clicked, !double_clicked)` and then `(clicked, double_clicked)`. The
    /// first frame is a real gesture and loads a radar; the guard only stops
    /// the second frame loading it again on top of the camera reset.
    #[test]
    fn a_ctrl_double_click_loads_once_on_the_first_release_and_not_again() {
        assert!(
            nearest_s_band_click(ctrl(), true, false),
            "first release of a double-click is an ordinary click and does fire"
        );
        assert!(
            !nearest_s_band_click(ctrl(), true, true),
            "second release must not fire a redundant reload"
        );
    }

    /// The precedence rule, on the real catalog and at the real opening zoom.
    ///
    /// This is the one that decides whether the feature works in the
    /// application at all rather than only in this module. `pane_canvas`
    /// hit-tests a nine-point halo around every site marker, and the app
    /// opens a pane at four kilometres per point, so that halo is 36 km of
    /// ground. Each downtown this feature exists for sits *inside* its
    /// TDWR's halo at that zoom, so any call site that lets a marker hit win
    /// answers Ctrl+click on downtown Dallas with TDAL.
    #[test]
    fn a_site_marker_must_not_swallow_the_gesture_at_the_zoom_the_app_opens_on() {
        let sites = real_sites();
        let halo_km = startup_marker_halo_km();
        assert_eq!(halo_km, 36.0);
        for (place, lat, lon, terminal, wsr88d) in [
            ("Dallas", 32.7767, -96.7970, "TDAL", "KFWS"),
            ("Chicago", 41.8781, -87.6298, "TORD", "KLOT"),
            ("Atlanta", 33.7490, -84.3880, "TATL", "KFFC"),
            ("San Juan", 18.4655, -66.1057, "TSJU", "TJUA"),
        ] {
            let terminal_km = distance_to(&sites, terminal, lat, lon);
            println!(
                "{place}: {terminal} is {terminal_km:.2} km away, inside the \
                 {halo_km:.0} km marker halo at the opening zoom"
            );
            assert!(
                terminal_km < halo_km,
                "{place}: {terminal} at {terminal_km:.2} km is inside the halo, \
                 which is what makes the precedence rule load-bearing"
            );
            // So the marker has to stand down while the chord is held...
            assert!(!site_marker_click_allowed(ctrl()));
            // ...and then the gesture answers with the S-band radar.
            let choice = nearest_s_band_site(lat, lon, &sites).expect("covered");
            assert_eq!(choice.id, wsr88d, "{place}");
        }
        // An unmodified click still belongs to the marker: clicking a site's
        // box is how the analyst loads that site on purpose.
        assert!(site_marker_click_allowed(egui::Modifiers::default()));
        assert!(site_marker_click_allowed(egui::Modifiers {
            shift: true,
            ..Default::default()
        }));
        assert!(site_marker_click_allowed(egui::Modifiers {
            ctrl: true,
            command: true,
            alt: true,
            ..Default::default()
        }));
    }

    /// The halo and the opening zoom are restated in this module because the
    /// crate's layering will not let it reach the private constants that own
    /// them. Restated numbers rot, so this reads the two owning files and
    /// fails when either moves.
    #[test]
    fn the_marker_halo_this_module_assumes_is_the_one_the_pane_uses() {
        let source_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let pane = source_root.join("pane_canvas.rs");
        let app = source_root.join("app.rs");
        let (Ok(pane), Ok(app)) = (
            std::fs::read_to_string(&pane),
            std::fs::read_to_string(&app),
        ) else {
            println!("pane_canvas.rs / app.rs not beside this module; halo not cross-checked");
            return;
        };
        for declaration in [
            "const SITE_MARKER_HALF: f32 = 5.0;",
            "const SITE_CLICK_SLACK: f32 = 4.0;",
        ] {
            assert!(
                pane.contains(declaration),
                "pane_canvas.rs no longer declares `{declaration}`; \
                 SITE_MARKER_HIT_POINTS ({SITE_MARKER_HIT_POINTS}) is now a guess"
            );
        }
        assert!(
            app.contains("const PLACEHOLDER_KM_PER_POINT: f32 = 4.0;"),
            "app.rs no longer opens a pane at 4.0 km per point; \
             STARTUP_KM_PER_POINT ({STARTUP_KM_PER_POINT}) is now a guess"
        );
        assert_eq!(SITE_MARKER_HIT_POINTS, 5.0 + 4.0);
        assert_eq!(marker_halo_km(STARTUP_KM_PER_POINT), 36.0);
        // At the widest the camera goes the halo is a quarter of the fence,
        // so this is not a startup-only concern.
        assert!(marker_halo_km(50.0) > MAX_SITE_RANGE_KM * 0.9);
    }

    /// The file this application actually reads at startup, when it is on
    /// this machine: same classification, same answers. The cache carries
    /// `f32`-rounded positions, which is what makes it worth re-checking.
    #[test]
    fn the_shipped_site_cache_agrees_with_the_transcript() {
        let Some(path) = shipped_cache_path() else {
            println!("no cache directory on this platform; transcript not cross-checked");
            return;
        };
        let Ok(text) = std::fs::read_to_string(&path) else {
            println!(
                "{} has not been written yet; transcript not cross-checked",
                path.display()
            );
            return;
        };
        // Same four-column tab-separated form `sites_service::parse_cache`
        // reads: id, latitude, longitude, name.
        let cached = text
            .lines()
            .filter_map(|line| {
                let mut fields = line.split('\t');
                let id = fields.next()?.trim();
                if id.is_empty() {
                    return None;
                }
                let latitude_deg = fields.next()?.trim().parse().ok()?;
                let longitude_deg = fields.next()?.trim().parse().ok()?;
                Some(LocatedSite {
                    id: id.to_owned(),
                    name: fields.next().map(str::to_owned),
                    latitude_deg,
                    longitude_deg,
                })
            })
            .collect::<Vec<_>>();
        assert!(
            cached.len() > 150,
            "{} holds only {} sites",
            path.display(),
            cached.len()
        );
        println!(
            "cross-checking {} real cached sites from {}",
            cached.len(),
            path.display()
        );
        let transcript = real_catalog();
        for site in &cached {
            if let Some(row) = transcript.iter().find(|row| row.site.id == site.id) {
                assert!(
                    great_circle_km(
                        site.latitude_deg,
                        site.longitude_deg,
                        row.site.latitude_deg,
                        row.site.longitude_deg
                    ) < 0.05,
                    "{} moved between the transcript and the cache",
                    site.id
                );
            }
        }
        for (city, lat, lon, expected) in [
            ("Dallas", 32.7767, -96.7970, "KFWS"),
            ("Chicago", 41.8781, -87.6298, "KLOT"),
            ("Atlanta", 33.7490, -84.3880, "KFFC"),
            ("San Juan", 18.4655, -66.1057, "TJUA"),
        ] {
            let choice = nearest_s_band_site(lat, lon, &cached)
                .unwrap_or_else(|| panic!("{city} must resolve from the shipped cache"));
            println!(
                "shipped cache, {city}: {} at {:.2} km",
                choice.id, choice.distance_km
            );
            assert_eq!(choice.id, expected, "{city}");
        }
    }

    /// The site ids on real Level II volumes this machine has actually
    /// downloaded, run through the classifier. This is the end of the chain
    /// the gesture feeds: `nearest_s_band_site` returns an id,
    /// `App::start_live` hands that id to the live service, and the service
    /// writes files named for it. Every id that has ever come back down that
    /// pipe must classify as a radar of some kind — never `Other` — and the
    /// terminal ones must classify as terminal, or the exclusion is not
    /// doing anything.
    ///
    /// Skipped, with a note, on a machine that has never gone live.
    #[test]
    fn the_ids_on_real_cached_level2_volumes_all_classify() {
        let directory = crate::live_service::default_live_cache_dir();
        let Ok(entries) = std::fs::read_dir(&directory) else {
            println!(
                "{} does not exist; no cached volumes to classify",
                directory.display()
            );
            return;
        };
        let mut seen = std::collections::BTreeMap::new();
        for entry in entries.flatten() {
            let name = entry.file_name();
            let Some(name) = name.to_str() else {
                continue;
            };
            // `KABR20260818_064314_RT698_V06`: the id runs up to the first
            // digit of the volume timestamp.
            let id = name
                .chars()
                .take_while(|character| character.is_ascii_alphabetic())
                .collect::<String>();
            if id.len() != 4 {
                continue;
            }
            seen.insert(id.clone(), classify_site(&id));
        }
        if seen.is_empty() {
            println!("{} holds no volumes yet", directory.display());
            return;
        }
        println!(
            "classifying {} site ids from real cached Level II volumes in {}",
            seen.len(),
            directory.display()
        );
        let transcript = real_catalog();
        for (id, class) in &seen {
            println!("  {id} -> {class:?}");
            assert_ne!(
                *class,
                SiteClass::Other,
                "{id} has served a real Level II volume, so it is a radar"
            );
            if let Some(row) = transcript.iter().find(|row| &row.site.id == id) {
                let expected = match row.station_type {
                    "TDWR" => SiteClass::Tdwr,
                    _ => SiteClass::Wsr88d,
                };
                assert_eq!(*class, expected, "{id}");
            }
        }
        // A cache with terminal volumes in it is the interesting case: those
        // ids exist, they are loadable, and this gesture still must not pick
        // them.
        let terminals = seen
            .iter()
            .filter(|(_, class)| **class == SiteClass::Tdwr)
            .count();
        println!("of which {terminals} are terminal radars the gesture will not pick");
    }

    /// Where `sites_service::cache_path` puts the site directory. Duplicated
    /// rather than called because that function is private to its module.
    fn shipped_cache_path() -> Option<std::path::PathBuf> {
        let base = if let Some(path) = std::env::var_os("LOCALAPPDATA") {
            std::path::PathBuf::from(path)
                .join("FahrenheitResearch")
                .join("RadarWorkstation")
                .join("cache")
        } else {
            std::path::PathBuf::from(std::env::var_os("XDG_CACHE_HOME")?).join("radar-workstation")
        };
        Some(base.join("radar-sites.tsv"))
    }
}
